### ISSUE TITLE
Sistema icona menu in navigazione mobile

### ISSUE THREAD

**Issue by bellons91** [code4it-dev/c4it-blog#21]
![image](https://user-images.githubusercontent.com/6106586/108727345-c0e05100-7528-11eb-85e3-f2371f000a0a.png)

Basta metter
```css
button.post__ToggleTocButton-h8gzap-14 GDWrm svg{
    margin-top: 45%;
}
```

per averlo cosí

![image](https://user-images.githubusercontent.com/6106586/108727502-f08f5900-7528-11eb-9535-979be536fa49.png)
